import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Loader from "./components/loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Histare",
  description: "Generated by create next app",
    icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Critical Inline Loader */}
        <Loader />
        {children}
      </body>
    </html>
  );
}
